apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname_proxy" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  default.conf: |-
    upstream backend {
      server localhost:81;
    }

    server {
        listen       80;
        # was:
        #  server_name  localhost;

        # this should capture into $sub a hostname that matches pr123-some-service.<DNS_ZONE>
        server_name  ~^(?<sub>[Pp][Rr][0-9]+-[^.]+)\.{{ .Values.DNS_ZONE }};

        access_log /dev/stdout;
        error_log /dev/stderr;

        # location / {
        #     root   /usr/share/nginx/html;
        #     index  index.html index.htm;
        # }

        location / {
          proxy_pass       http://backend/user/$http_x_forwarded_user;
          proxy_set_header Host      $host;
          proxy_set_header X-Real-IP $remote_addr;
          add_header Content-Disposition 'attachment; filename="client.ovpn"';
          add_header Content-Type application/octet-stream;
        }

        location /configs/ {
          alias /usr/share/nginx/private/;
        }

        # todo(tamsky)
        # location /logout
    }
