apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname_proxy" . }}
  labels:
    app: {{ template "fullname_proxy" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        # TODO(tamsky) update when done
        # checksum/ui-config:    { include (print $.Template.BasePath "/dashboard.configmap.yaml") . | sha256sum }}
        # checksum/vpn-config:   { include (print $.Template.BasePath "/vpn.configmap.yaml") . | sha256sum }}
        # checksum/vpn-secret:   { include (print $.Template.BasePath "/vpn.secret.yaml") . | sha256sum }}
        # checksum/oauth-config: { include (print $.Template.BasePath "/oauth.configmap.yaml") . | sha256sum }}
        # checksum/oauth-secret: { include (print $.Template.BasePath "/oauth.secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
          # - name: source
          #   mountPath: /usr/share/nginx/html
        livenessProbe:
          tcpSocket:
            port: 80
        readinessProbe:
          tcpSocket:
            port: 80
        resources:
{{ toYaml .Values.nginx.resources | indent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ template "fullname_proxy" . }}
