---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname_oauth" . }}
  labels:
    app: {{ template "fullname_oauth" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.oauth.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/oauth.configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/oauth.secret.yaml") . | sha256sum }}
    spec:
      containers:
      # Sidecar oauth2_proxy container
      - name: {{ .Chart.Name }}
        image: "{{ .Values.oauth.image.repository }}:{{ .Values.oauth.image.tag }}"
        imagePullPolicy: {{ .Values.oauth.image.pullPolicy }}
        args:
          - "-config"
          - "/usr/share/oauth2_proxy/config"
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: client_id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: client_secret
        - name: OAUTH2_PROXY_COOKIE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: cookie_name
        - name: OAUTH2_PROXY_COOKIE_DOMAIN
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: cookie_domain
        - name: OAUTH2_PROXY_COOKIE_EXPIRE
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: cookie_expire
        - name: OAUTH2_PROXY_COOKIE_REFRESH
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: cookie_refresh
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: cookie_secret
        ports:
        - containerPort: {{ .Values.oauth.service.http.internalPort }}
        volumeMounts:
          - name: config
            mountPath: /usr/share/oauth2_proxy
        livenessProbe:
          tcpSocket:
            port: {{ .Values.oauth.service.http.internalPort }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.oauth.service.http.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "fullname" . }}
