apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teleport-node.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "teleport-node.name" . }}
    app.kubernetes.io/component: "{{ .Values.name }}"
    helm.sh/chart: {{ include "teleport-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
